### ISSUE TITLE
업데이트 버튼 이미지 변경

### ISSUE THREAD

**Issue by sangcheol12** [SWM-Codection/gitea#12]
<img width="296" alt="스크린샷 2024-07-11 오후 4 00 33" src="https://github.com/SWM-Codection/gitea/assets/53574961/04f0e71b-e269-4bb3-8541-18a2ea60050e">

위의 + 버튼이 업데이트인데 UI가 이해하기 어려움 수정하면 좋을 듯

**Comment by cloudchamb3r** [comment]
의존성 항목은 + 로 유지해도 괜찮을까요?
