### ISSUE TITLE
PR 생성시 AI 리뷰 호출 시간 감소 필요

### ISSUE THREAD

**Issue by sangcheol12** [SWM-Codection/gitea#41]
현재 변화 된 파일 목록 가져와 파일의 전체 목록을 AI에게 보내는 구조로 작성되어 있음

### 테스트 조건
파일 수 : 파일 2개
파일 라인 : 각 30줄 이내
네트워크 : 소마 센터 WIFI

### 소요 시간
평균 약 15초 소요

개선 방향
AI 코멘트 생성 코드를 코루틴의 GlobalScope.launch처럼 호출해서 독립적으로 시행되도록 수정 예정

**Comment by cloudchamb3r** [comment]
해결된 문제이므로 닫겠습니다
