### ISSUE TITLE
현재 discussion에 대한 요청의 에러 처리 방식을 바꿔야 합니다.

### ISSUE THREAD

**Issue by Lieslot** [SWM-Codection/gitea#89]
발견 경위
---
Discussion 서버에서 404가 발생했음에도 불구하고 gitea에선 error가 발생하지 않는 문제가 있었습니다.

![스크린샷 2024-09-25 104358](https://github.com/user-attachments/assets/cb4f3c76-617a-40d4-a26a-fa2c3325f143)
![스크린샷 2024-09-25 104433](https://github.com/user-attachments/assets/0252c7cd-73c4-43a5-9da4-3f7ce24fc9b6)

처음에는 디스커션 서버의 exception handler의 문제가 있다고 판단했지만 전혀 문제가 없었습니다.
그래서 resty client 쪽을 뜯어보니 status code가 400이상 일 때 에러를 뱉는 로직이 없다는 걸 발견했습니당.

문제가 되는 것
---

현재 디스커션 서버에 대한 요청을 담당하고 있는 disscussion_client.go 파일 내부의 에러처리 로직을 보면 다음과 같습니다.

```

_, err := client.Request().SetBody(request).Delete("/discussion/comment") // resty_client의 err를 가져옴

if err != nil {
	log.Error("DeleteDiscussionComment failed: %s", err.Error())
	return fmt.Errorf("%w", err)
}

return nil
```

여기서 err는 response가 정상적인 status 코드를 뱉었느냐 아니냐와 별로 관계가 없습니다. 그냥 connection timeout이 나거나 응답 메시지에 대한 read가 실패했냐에 대한 에러입니다. resty의 Response 객체에는 400 이상의 status 코드를 받았는지 판단하는 IsError()라는 메소드가 존재하는데 resty client쪽 로직을 보면 이걸 확인하는 로직이 전무합니다.(에러에 대한 정보를 body에 담아서 전달하는 경우가 있으니 그걸 고려한 거 같기도 합니다.)

해결책
---

따라서 아래와 같은 로직으로 변경해야 됩니다.

```
	resp, err := client.Request().
		SetBody(request).
		Delete("/discussion/comment")
	if err != nil {

		return fmt.Errorf("failed to make DELETE /discussion/comment request: %w", err)
	}

	if err := handleResponse(resp); err != nil {
		return err
	}

	return nil
	
	// 에러 처리 로직
	// status code가 400 이상인지 확인하고 에러 처리
	func handleResponse(resp *resty.Response) error {
	
	if resp.IsError() {
		var errResp DiscussionErrorResponse
		if err := json.Unmarshal(resp.Body(), &errResp); err != nil { // 디스커션 서버의 ErrorResponse 객체 받기)
			log.Error("Failed to parse error response: %v", err)
			return fmt.Errorf("unexpected error: %s", resp.Status())
		}
		log.Error("API Error %d: %s", errResp.Status, errResp.message)
		return fmt.Errorf("api error %d: %s", errResp.Status, errResp.message)
	}
	return nil
}

```

**Comment by cloudchamb3r** [comment]
좋네요
